config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  post '/visitor' => 'visitors#create'
  get '/visitor' => 'visitors#index'
  root to: 'visitors#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :school, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    @visitor = Visitor.new
  end

  def new
  end

  def create
    @visitor = Visitor.new(visitor_params)
    respond_to do |format|
      if @visitor.save
        format.html {
         #flash[:notice] = "Thank you for sharing"
         render :index
        }
        format.js {
          flash.now[:notice] = "Thank you for sharing!!!!"
          render action: 'create'
          #render json: @visitor, status: :created, location: @visitor
        }
      else
        format.html {
         #flash[:alert] = "Error submitting"
         render :index
        }
        format.js {
          render action: 'create'
        }
      end
    end
  end


  private
  def visitor_params
    params.require(:visitor).permit(:name,:event_last,:email,:school, :event_next, :event_favourite, :comments)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', '#home', class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><a href="#survey">Survey</a></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Welcome to Leanportal" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "An app for curated conferences and networking events information" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Indie+Flower' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Hind+Siliguri'  %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Sumana'  %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%#= render 'layouts/navigation' %>
    </header>
      <div class='messages'>
      <%= render 'layouts/messages' %>
      </div>
      <%= yield %>
  </body>
</html>

app/views/visitors/_form.html.erb
<%= form_for @visitor, url: visitor_path, method: :post, remote: true  do |f| %>
   My name is <%= f.text_field :name, placeholder: "Name", required: true, autocomplete: :off %>
  <br>
   I went to <%= f.text_field :school, placeholder: "University Name", required: true, autocomplete: :off %>
  <br>
   The last event I went to is <%= f.text_field :event_last, autocomplete: :off  %>
  <br>
   The next event I want to go is <%= f.text_field :event_next, autocompelte: :off %>
  <br>
  My favourite event was <%= f.text_field :event_favourite, placeholder: "nwHack", autocomplete: :off %>
  <br>
   Some improvements I think the events need are <%= f.text_field :comments, placeholder: "Feedback please!", autocomplete: :off %>
   <br>
    Please keep me updated regarding this project at <%= f.email_field :email, placeholder: "abc@gmail.com", autocomplete: :off %>
    <br>
  <%= f.submit "Submit" %>
<% end %>

app/views/visitors/create.js.erb
//$('#survey-form').append('<%= j render partial: "layouts/messages" %>');
$('#survey').fadeOut(600, function() {
  $('#thankyou').fadeIn(600);
});

app/views/visitors/index.html.erb
<!-- Full Width Image Header with Logo -->
<!-- Image backgrounds are set within the full-width-pics.css file. -->
<section id="home" class='image-bg-fluid-height'>
  <div class="container-fluid">
    <div class='row-fluid'>
      <div class="centering text-center">
        <h1> Leanportal coming soon! </h1> <br>
          <div class='lead'>
          Please help us out by filling out the quick survey below!

          <br>
          We will pick two winners for a $50 starbucks gift card if you put in your email.
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Content Section -->
<section id="survey">
    <div class="container-fluid">
        <div class="row-fluid">
          <div class='spinner'>
            <div class='dot1'></div>
            <div class='dot2'></div>
           </div>
            <div class="col-lg-12">
              <div class='centering text-center'>
              <h1> Survey </h1>
              <p> Leanportal is looking to learn more about the events students attend in terms of conferences/events <br> 
                Please enter the following.  Leave blank if no answer<p>
                <div id="survey-form">
                  <%= render "form" %>
                </div>
              </div>
            </div>
        </div>
    </div>
</section>


<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class='footer-font'>Copyright &copy; Swapifi Technologies 2016</div>
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</footer>

app/views/visitors/new.html.erb
<%= form_for @visitor, url: {action: "create"} do |f| %>
  My name is <%= f.text_field :name, :placeholder => "Edwin Tsang" %>
  <br>
   I went to <%= f.text_field :school %>
  <br>
   The last event I went to is <%= f.text_field :event_last %>
  <br>
   The next event I want to go is <%= f.text_field :event_next %>
  <br>
   Events I might be interested in includes <%= f.text_field :event_interested %>
  <br>
  My favourite event was <%= f.text_field :event_favourite %>
  <br>
   Some improvements I think the events need  are <%= f.text_field :comments %>
   <br>
    Please keep me updated regarding this project at <%= f.text_field :email %>
  <%= f.submit "Submit" %>>
<% end %>